---
- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ cert_item.domains | first | replace('*.', '') }}/cert.pem
  register: letsencrypt_cert

- name: Stop services to allow certbot to generate a cert.
  service:
    name: "{{ item }}"
    state: stopped
  when: not letsencrypt_cert.stat.exists
  with_items: "{{ certbot_create_standalone_stop_services }}"

- name: Add renew options to cli.ini file
  copy:
    path: /etc/letsencrypt/cli.ini
    content: "{{ certbot_cli_options }}"
  when: certbot_cli_options is defined

- name: Generate new certificate if one doesn't exist.
  command: "{{ certbot_create_command }}"
  when: not letsencrypt_cert.stat.exists

- name: Start services after cert has been generated.
  service:
    name: "{{ item }}"
    state: started
  when: not letsencrypt_cert.stat.exists
  with_items: "{{ certbot_create_standalone_stop_services }}"
