---
- name: Install Certbot.
  package: "name={{ item }} state=present"
  with_items: "{{ certbot_package }}"

- name: Set Certbot script variable.
  set_fact:
    certbot_script: "{{ certbot_package }}"
